@cds.persistence.exists
@cds.persistence.calcview
entity SAP_HANA_DEMOCONTENT_EPM_MODELS_TEST {
  key CALMONTH              : hana.VARCHAR(6)  @title: 'CALMONTH';
      CALQUARTER            : hana.VARCHAR(5)  @title: 'CALQUARTER';
      CALWEEK               : hana.VARCHAR(6)  @title: 'CALWEEK';
      DATETIMESTAMP         : Timestamp        @title: 'DATETIMESTAMP';
      DATETIME_SAP          : hana.VARCHAR(14) @title: 'DATETIME_SAP';
      DATE_SAP              : hana.VARCHAR(8)  @title: 'DATE_SAP';
      DATE_SQL              : Date             @title: 'DATE_SQL';
      DAY                   : hana.VARCHAR(2)  @title: 'DAY';
      DAY_INT               : hana.TINYINT     @title: 'DAY_INT';
      DAY_OF_WEEK           : hana.VARCHAR(2)  @title: 'DAY_OF_WEEK';
      DAY_OF_WEEK_INT       : hana.TINYINT     @title: 'DAY_OF_WEEK_INT';
      HOUR                  : hana.VARCHAR(2)  @title: 'HOUR';
      HOUR_INT              : hana.TINYINT     @title: 'HOUR_INT';
      MINUTE                : hana.VARCHAR(2)  @title: 'MINUTE';
      MINUTE_INT            : hana.TINYINT     @title: 'MINUTE_INT';
      MONTH                 : hana.VARCHAR(2)  @title: 'MONTH';
      MONTH_INT             : hana.TINYINT     @title: 'MONTH_INT';
      MONTH_LAST_DAY        : hana.TINYINT     @title: 'MONTH_LAST_DAY';
      QUARTER               : hana.VARCHAR(2)  @title: 'QUARTER';
      QUARTER_INT           : hana.TINYINT     @title: 'QUARTER_INT';
      SECOND                : hana.VARCHAR(2)  @title: 'SECOND';
      SECOND_INT            : hana.TINYINT     @title: 'SECOND_INT';
      TZNTSTMPL             : Decimal(21, 7)   @title: 'TZNTSTMPL';
      TZNTSTMPS             : Decimal(15, 0)   @title: 'TZNTSTMPS';
      WEEK                  : hana.VARCHAR(2)  @title: 'WEEK';
      WEEK_INT              : hana.TINYINT     @title: 'WEEK_INT';
      WEEK_YEAR             : hana.VARCHAR(4)  @title: 'WEEK_YEAR';
      WEEK_YEAR_INT         : Integer          @title: 'WEEK_YEAR_INT';
      YEAR                  : hana.VARCHAR(4)  @title: 'YEAR';
      YEAR_INT              : Integer          @title: 'YEAR_INT';
  key PARTNERID             : String(10)       @title: 'PARTNERID';
      PARTNERROLE           : String(3)        @title: 'PARTNERROLE';
      EMAILADDRESS          : String(255)      @title: 'EMAILADDRESS';
      COMPANYNAME           : String(80)       @title: 'COMPANYNAME';
      LEGALFORM             : String(10)       @title: 'LEGALFORM';
      CITY                  : hana.VARCHAR(40) @title: 'CITY';
      POSTALCODE            : String(10)       @title: 'POSTALCODE';
      BUILDING              : String(10)       @title: 'BUILDING';
      STREET                : String(60)       @title: 'STREET';
      COUNTRY               : String(3)        @title: 'COUNTRY';
      REGION                : String(4)        @title: 'REGION';
  key PRODUCTID             : String(10)       @title: 'PRODUCTID';
      PRODUCT_TYPECODE      : String(2)        @title: 'PRODUCT_TYPECODE';
      PRODUCT_CATEGORY      : hana.VARCHAR(40) @title: 'PRODUCT_CATEGORY';
      PRODUCT_CURRENCY      : String(5)        @title: 'PRODUCT_CURRENCY';
      PRODUCT_WEIGHTUNIT    : String(3)        @title: 'PRODUCT_WEIGHTUNIT';
      PRODUCT_WEIGHTMEASURE : Decimal(13, 3)   @title: 'PRODUCT_WEIGHTMEASURE';
      PRODUCT_PRICE         : Decimal(15, 2)   @title: 'PRODUCT_PRICE';
      PRODUCTPICURL         : String(255)      @title: 'PRODUCTPICURL';
      SUPPLIER_ID           : String(10)       @title: 'SUPPLIER_ID';
      COMPANYNAME_1         : String(80)       @title: 'COMPANYNAME_1';
      SUPPLIER_CITY         : hana.VARCHAR(40) @title: 'SUPPLIER_CITY';
      SUPPLIER_POSTALCODE   : String(10)       @title: 'SUPPLIER_POSTALCODE';
      SUPPLIER_STREET       : String(60)       @title: 'SUPPLIER_STREET';
      SUPPLIER_BUILDING     : String(10)       @title: 'SUPPLIER_BUILDING';
      SUPPLIER_COUNTRY      : String(3)        @title: 'SUPPLIER_COUNTRY';
      SUPPLIER_REGION       : String(4)        @title: 'SUPPLIER_REGION';
      PRODUCT_NAME          : String(1024)     @title: 'PRODUCT_NAME';
      PRODUCT_DESCRIPTION   : String(1024)     @title: 'PRODUCT_DESCRIPTION';
  key SALESORDERID          : String(10)       @title: 'SALESORDERID';
  key SALESORDERITEM        : String(10)       @title: 'SALESORDERITEM';
      NETAMOUNT             : Decimal(15, 2)   @title: 'NETAMOUNT';
};
